repos:
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: golangci-lint-mod
        args: [--fix]
      - id: go-test-mod

  - repo: local
    hooks:
      - id: encrypt-inputs
        name: encrypt-inputs
        entry: ./hack/encrypt-inputs.sh
        language: system
        pass_filenames: false
